use_frameworks!
platform :ios, '11.0'

target 'Tsuchi_Example' do
  pod 'Tsuchi', :path => '../'
  pod 'I'

  target 'Tsuchi_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2'
  pod 'Nimble', '~> 7.3'
  pod 'FBSnapshotTestCase' , '~> 2.1'
  pod 'Nimble-Snapshots' , '~> 6.3'
  end
end
