use_frameworks!
platform :ios, '11.0'
inhibit_all_warnings!

target 'Tsuchi_Example' do
  pod 'Tsuchi', :path => '../'
  pod 'I'

  target 'Tsuchi_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
    pod 'FBSnapshotTestCase' , '~> 2.1'
    pod 'Nimble-Snapshots'
  end
end
